
```{r}
require(reml)
```

## What example functions would look like
```{r}
eml_dataset <- function(x)
  as(x, "eml:dataset")

eml_write <- function(x, file = NULL){
  eml <- as(x, "eml:eml")
  doc <- newXMLDoc(node=eml)
  saveXML(doc, file=file)
}
```

some testing data

```{r}

dat = data.frame(river = c("SAC",  "SAC",   "AM"),
                 spp   = c("king",  "king", "ccho"),
                 stg   = c("smolt", "parr", "smolt"),
                 ct    = c(293L,    410L,    210L))
```


New metadata format

```{r}
metadata <- 
  list("river" = list("river",
                      "River site used for collection",
                      c(SAC = "The Sacramento River", AM = "The American River")),
       "spp" = list("spp",
                    "Species common name", 
                    c(king = "King Salmon", ccho = "Coho Salmon")),
       "stg" = list("stg",
                    "Life Stage", 
                    c(parr = "third life stage", smolt = "fourth life stage")),
       "ct"  = list("ct",
                    "count", 
                    "number"))
```

### Coercion methods 

Detect types 

```{r}
metadata <- detect_class(dat, metadata)
```

Coerce a factor definitions into a nominal,

```{r}
as(metadata$river[[3]], "eml:nominal")
```

or coerce the entire list into an attribute node (includes the above coercion)

```{r}
as(metadata$river, "eml:attribute")
```

Or all metadata lists at once:

```{r}
as(metadata, "eml:attributeList")
```

```{r}
new("eml:dataSet", dataTable = new("eml:dataTable", attributeList = as(metadata, "eml:attributeList")) )
```
