setClass('eml-2.1.1')
setClass('xml_attribute', contains = 'character')

setClass('i18nNonEmptyStringType', contains='character')
setClass('ReferencesGroup', slots = c('references' = 'character'), contains = c('eml-2.1.1'))
setClass('ConstraintBaseGroup', slots = c('constraintName' = 'character', 'constraintDescription' = 'character'), contains = c('eml-2.1.1'))
setClass('xs:float', contains = 'numeric')
setClass('xs:string', contains = 'character')
setClass('xs:anyURI', contains = 'character')
setClass('xs:time', contains = 'character')
setClass('xs:decimal', contains = 'numeric')
setClass('xs:int', contains = 'integer')
setClass('xs:unsignedInt', contains = 'integer')
setClass('xs:unsignedLong', contains = 'integer')
setClass('xs:long', contains = 'integer')
setClass('xs:integer', contains = 'integer')
setClass('xs:boolean', contains = 'logical')
setClass('xs:date', contains = 'Date')


#####  inst/xsd/stmml.xsd  ####


setClass('coordinate2Type', contains = 'character')
setClass('coordinate3Type', contains = 'character')
setClass('dataTypeType', contains = 'character')
setClass('sizeType', contains = 'character')
setClass('delimiterType', contains = 'character')
setClass('floatArrayType', contains = 'character')
setClass('matrixType', contains = 'character')
setClass('countType', contains = 'character')
setClass('idType', contains = 'character')
setClass('errorBasisType', contains = 'character')
setClass('maxType', contains = 'character')
setClass('minType', contains = 'character')
setClass('namespaceRefType', contains = 'character')
setClass('refType', contains = 'character')
setClass('metadataType', contains = 'character')
setClass('dimensionType', contains = 'character')
setClass('unitsType', contains = 'character')
setClass('ListOfarray', contains = 'list')
setClass('ListOfunitList', contains = 'list')
setClass('ListOfannotation', contains = 'list')
setClass('ListOfdescription', contains = 'list')
setClass('ListOfentry', contains = 'list')
setClass('ListOfmetadata', contains = 'list')
setClass('ListOfunitType', contains = 'list')
setClass('ListOfunit', contains = 'list')
setClass('ListOfdimension', contains = 'list')
setClass('eml:array', slots = c('dataType' = 'xml_attribute', 'errorValues' = 'xml_attribute', 'errorBasis' = 'xml_attribute', 'minValues' = 'xml_attribute', 'maxValues' = 'xml_attribute', 'units' = 'xml_attribute', 'delimiter' = 'xml_attribute', 'size' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('scalar', slots = c('dataType' = 'xml_attribute', 'errorValue' = 'xml_attribute', 'errorBasis' = 'xml_attribute', 'minValue' = 'xml_attribute', 'maxValue' = 'xml_attribute', 'units' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('eml:matrix', slots = c('dataType' = 'xml_attribute', 'delimiter' = 'xml_attribute', 'rows' = 'xml_attribute', 'columns' = 'xml_attribute', 'units' = 'xml_attribute', 'matrixType' = 'xml_attribute', 'errorValues' = 'xml_attribute', 'errorBasis' = 'xml_attribute', 'minValues' = 'xml_attribute', 'maxValues' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('eml:table', slots = c('array' = 'ListOfarray', 'rows' = 'xml_attribute', 'columns' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('eml:list', slots = c('type' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('link', slots = c('from' = 'xml_attribute', 'to' = 'xml_attribute', 'ref' = 'xml_attribute', 'role' = 'xml_attribute', 'href' = 'xml_attribute', 'type' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('action', slots = c('type' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('actionList', slots = c('type' = 'xml_attribute', 'order' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('object', slots = c('type' = 'xml_attribute', 'count' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('observation', slots = c('type' = 'xml_attribute', 'count' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('stmml', contains = c('eml-2.1.1'))
setClass('dictionary', slots = c('unitList' = 'ListOfunitList', 'annotation' = 'ListOfannotation', 'description' = 'ListOfdescription', 'entry' = 'ListOfentry', 'href' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('entry', slots = c('definition' = 'character', 'alternative' = 'character', 'annotation' = 'character', 'description' = 'character', 'enumeration' = 'character', 'relatedEntry' = 'character', 'dataType' = 'xml_attribute', 'rows' = 'xml_attribute', 'columns' = 'xml_attribute', 'recommendedUnits' = 'xml_attribute', 'unitType' = 'xml_attribute', 'minExclusive' = 'xml_attribute', 'minInclusive' = 'xml_attribute', 'maxExclusive' = 'xml_attribute', 'maxInclusive' = 'xml_attribute', 'totalDigits' = 'xml_attribute', 'fractionDigits' = 'xml_attribute', 'length' = 'xml_attribute', 'minLength' = 'xml_attribute', 'maxLength' = 'xml_attribute', 'units' = 'xml_attribute', 'whiteSpace' = 'xml_attribute', 'pattern' = 'xml_attribute', 'term' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('definition', contains = c('character', 'eml-2.1.1'))
setClass('description', slots = c('eml:class' ='xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('enumeration', slots = c('annotation' = 'character', 'value' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('alternative', slots = c('type' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('relatedEntry', slots = c('type' = 'xml_attribute', 'href' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('annotation', slots = c('documentation' = 'character', 'appinfo' = 'character', 'source' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('documentation', contains = c('character', 'eml-2.1.1'))
setClass('appinfo', slots = c('source' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('metadata', slots = c('name' = 'xml_attribute', 'content' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('metadataList', slots = c('metadata' = 'ListOfmetadata'), contains = c('eml-2.1.1'))
setClass('dimension', slots = c('name' = 'xml_attribute', 'power' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('unitList', slots = c('unitType' = 'ListOfunitType', 'unit' = 'ListOfunit', 'href' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('unitType', slots = c('dimension' = 'ListOfdimension', 'id' = 'xml_attribute', 'name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('unit', slots = c('description' = 'character', 'annotation' = 'character', 'id' = 'xml_attribute', 'abbreviation' = 'xml_attribute', 'name' = 'xml_attribute', 'parentSI' = 'xml_attribute', 'unitType' = 'xml_attribute', 'multiplierToSI' = 'xml_attribute', 'constantToSI' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('dataGroup', slots = c('list' = 'character', 'scalar' = 'character'), contains = c('eml-2.1.1'))


#####  inst/xsd/eml-text.xsd  ####


setClass('ListOfsection', contains = 'list')
setClass('ListOfpara', contains = 'list')
setClass('ListOfvalue', contains = 'list')
setClass('ListOflistitem', contains = 'list')
setClass('emphasis', slots = c('value' = 'ListOfvalue'), contains = c('character', 'eml-2.1.1'))
setClass('literalLayout', slots = c('value' = 'ListOfvalue'), contains = c('character', 'eml-2.1.1'))
setClass('ulink', slots = c('citetitle' = 'i18nString', 'url' = 'xml_attribute'), contains = c('character', 'eml-2.1.1'))
setClass('listitem', slots = c('para' = 'ParagraphType', 'itemizedlist' = 'ListType', 'orderedlist' = 'ListType'), contains = c('eml-2.1.1'))
setClass('TextType', slots = c('section' = 'ListOfsection', 'para' = 'ListOfpara'), contains = c('character', 'eml-2.1.1'))
setClass('ParagraphType', slots = c('value' = 'ListOfvalue', 'itemizedlist' = 'ListType', 'orderedlist' = 'ListType', 'emphasis' = 'emphasis', 'subscript' = 'SubSuperScriptType', 'superscript' = 'SubSuperScriptType', 'literalLayout' = 'literalLayout', 'ulink' = 'ulink'), contains = c('character', 'eml-2.1.1'))
setClass('SectionType', slots = c('title' = 'i18nString', 'para' = 'ParagraphType', 'section' = 'SectionType'), contains = c('eml-2.1.1'))
setClass('ListType', slots = c('listitem' = 'ListOflistitem'), contains = c('eml-2.1.1'))
setClass('SubSuperScriptType', slots = c('value' = 'ListOfvalue', 'subscript' = 'SubSuperScriptType', 'superscript' = 'SubSuperScriptType'), contains = c('character', 'eml-2.1.1'))
setClass('i18nString', contains = c('xs:string', 'eml-2.1.1'))
setClass('text', contains = 'TextType')
setClass('section', contains = 'SectionType')
setClass('para', contains = 'ParagraphType')
setClass('value', contains = 'i18nString')
setClass('itemizedlist', contains = 'ListType')
setClass('orderedlist', contains = 'ListType')
setClass('value', contains = 'i18nString')
setClass('subscript', contains = 'SubSuperScriptType')
setClass('superscript', contains = 'SubSuperScriptType')
setClass('value', contains = 'i18nString')
setClass('citetitle', contains = 'i18nString')
setClass('title', contains = 'i18nString')
setClass('para', contains = 'ParagraphType')
setClass('section', contains = 'SectionType')
setClass('para', contains = 'ParagraphType')
setClass('itemizedlist', contains = 'ListType')
setClass('orderedlist', contains = 'ListType')
setClass('value', contains = 'i18nString')
setClass('subscript', contains = 'SubSuperScriptType')
setClass('superscript', contains = 'SubSuperScriptType')


#####  inst/xsd/eml-documentation.xsd  ####


setClass('moduleDocs', slots = c('moduleName' = 'xs:string', 'moduleDescription' = 'TextType', 'recommendedUsage' = 'xs:string', 'standAlone' = 'xs:string'), contains = c('eml-2.1.1'))
setClass('moduleName', contains = 'xs:string')
setClass('moduleDescription', contains = 'TextType')
setClass('recommendedUsage', contains = 'xs:string')
setClass('standAlone', contains = 'xs:string')
setClass('tooltip', contains = 'xs:string')
setClass('summary', contains = 'xs:string')
setClass('description', contains = 'TextType')
setClass('example', contains = 'TextType')
setClass('lineage', contains = 'xs:string')
setClass('module', contains = 'xs:string')


#####  inst/xsd/eml-unitTypeDefinitions.xsd  ####


setClass('StandardUnitDictionary', contains = 'character')
setClass('LengthUnitType', contains = 'character')
setClass('MassUnitType', contains = 'character')
setClass('otherUnitType', contains = 'character')
setClass('angleUnitType', contains = 'character')


#####  inst/xsd/eml-party.xsd  ####


setClass('RoleType', contains = 'character')
setClass('ListOfaddress', contains = 'list')
setClass('ListOfphone', contains = 'list')
setClass('ListOfelectronicMailAddress', contains = 'list')
setClass('ListOfonlineUrl', contains = 'list')
setClass('ListOfuserId', contains = 'list')
setClass('ListOfsalutation', contains = 'list')
setClass('ListOfgivenName', contains = 'list')
setClass('ListOfdeliveryPoint', contains = 'list')
setClass('phone', slots = c('phonetype' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('userId', slots = c('directory' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('ResponsibleParty', slots = c('individualName' = 'Person', 'organizationName' = 'character', 'positionName' = 'character', 'address' = 'ListOfaddress', 'phone' = 'ListOfphone', 'electronicMailAddress' = 'ListOfelectronicMailAddress', 'onlineUrl' = 'ListOfonlineUrl', 'userId' = 'ListOfuserId', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('Person', slots = c('salutation' = 'ListOfsalutation', 'givenName' = 'ListOfgivenName', 'surName' = 'character'), contains = c('eml-2.1.1'))
setClass('Address', slots = c('deliveryPoint' = 'ListOfdeliveryPoint', 'city' = 'character', 'administrativeArea' = 'character', 'postalCode' = 'character', 'country' = 'character', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('individualName', contains = 'Person')
setClass('address', contains = 'Address')
setClass('electronicMailAddress', contains = 'character')
setClass('onlineUrl', contains = 'xs:anyURI')
setClass('salutation', contains = 'character')
setClass('givenName', contains = 'character')
setClass('deliveryPoint', contains = 'character')
setClass('party', contains = 'ResponsibleParty')


#####  inst/xsd/eml-resource.xsd  ####


setClass('KeyTypeCode', contains = 'character')
setClass('yearDate', contains = 'character')
setClass('IDType', contains = 'character')
setClass('SystemType', contains = 'character')
setClass('ScopeType', contains = 'character')
setClass('FunctionType', contains = 'character')
setClass('NonEmptyStringType', contains = 'character')
setClass('ListOfalternateIdentifier', contains = 'list')
setClass('ListOftitle', contains = 'list')
setClass('ListOfcreator', contains = 'list')
setClass('ListOfmetadataProvider', contains = 'list')
setClass('ListOfassociatedParty', contains = 'list')
setClass('ListOfkeywordSet', contains = 'list')
setClass('ListOfkeyword', contains = 'list')
setClass('ListOfadditionalInfo', contains = 'list')
setClass('ListOfdistribution', contains = 'list')
setClass('ListOfparameterDefinition', contains = 'list')
setClass('ListOfmediumFormat', contains = 'list')
setClass('ListOfparameter', contains = 'list')
setClass('ListOfvalue', contains = 'list')
setClass('alternateIdentifier', slots = c('system' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('associatedParty', slots = c('role' = 'RoleType'), contains = c('ResponsibleParty', 'eml-2.1.1'))
setClass('keywordSet', slots = c('keyword' = 'ListOfkeyword', 'keywordThesaurus' = 'character'), contains = c('eml-2.1.1'))
setClass('keyword', contains = c('i18nNonEmptyStringType', 'character', 'eml-2.1.1'))
setClass('references', slots = c('system' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('schemeName', slots = c('system' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('parameterDefinition', slots = c('name' = 'character', 'definition' = 'character', 'defaultValue' = 'character'), contains = c('eml-2.1.1'))
setClass('parameter', slots = c('name' = 'character', 'value' = 'character'), contains = c('eml-2.1.1'))
setClass('value', contains = c('NonEmptyStringType', 'eml-2.1.1'))
setClass('ResourceGroup', slots = c('alternateIdentifier' = 'ListOfalternateIdentifier', 'shortName' = 'character', 'title' = 'ListOftitle', 'creator' = 'ListOfcreator', 'metadataProvider' = 'ListOfmetadataProvider', 'associatedParty' = 'ListOfassociatedParty', 'pubDate' = 'yearDate', 'language' = 'character', 'series' = 'character', 'abstract' = 'TextType', 'keywordSet' = 'ListOfkeywordSet', 'additionalInfo' = 'ListOfadditionalInfo', 'intellectualRights' = 'TextType', 'distribution' = 'ListOfdistribution', 'coverage' = 'Coverage'), contains = c('eml-2.1.1'))
setClass('ReferencesGroup', slots = c('references' = 'character'), contains = c('eml-2.1.1'))
setClass('DistributionType', slots = c('online' = 'OnlineType', 'offline' = 'OfflineType', 'inline' = 'InlineType', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('ConnectionDefinitionType', slots = c('schemeName' = 'xs:string', 'description' = 'TextType', 'parameterDefinition' = 'ListOfparameterDefinition', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('InlineType', contains = c('character', 'eml-2.1.1'))
setClass('OfflineType', slots = c('mediumName' = 'character', 'mediumDensity' = 'character', 'mediumDensityUnits' = 'character', 'mediumVolume' = 'character', 'mediumFormat' = 'ListOfmediumFormat', 'mediumNote' = 'character'), contains = c('eml-2.1.1'))
setClass('OnlineType', slots = c('onlineDescription' = 'character', 'url' = 'UrlType', 'connection' = 'ConnectionType', 'connectionDefinition' = 'ConnectionDefinitionType'), contains = c('eml-2.1.1'))
setClass('UrlType', slots = c('function' = 'xml_attribute'), contains = c('xs:anyURI', 'eml-2.1.1'))
setClass('ConnectionType', slots = c('connectionDefinition' = 'ConnectionDefinitionType', 'parameter' = 'ListOfparameter', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('i18nNonEmptyStringType', slots = c('value' = 'ListOfvalue'), contains = c('character', 'eml-2.1.1'))
setClass('title', contains = 'character')
setClass('creator', contains = 'ResponsibleParty')
setClass('metadataProvider', contains = 'ResponsibleParty')
setClass('role', contains = 'RoleType')
setClass('pubDate', contains = 'yearDate')
setClass('abstract', contains = 'TextType')
setClass('additionalInfo', contains = 'TextType')
setClass('intellectualRights', contains = 'TextType')
setClass('distribution', contains = 'DistributionType')

setClass('online', contains = 'OnlineType')
setClass('offline', contains = 'OfflineType')
setClass('inline', contains = 'InlineType')
setClass('description', contains = 'TextType')
setClass('mediumFormat', contains = 'character')
setClass('url', contains = 'UrlType')
setClass('connection', contains = 'ConnectionType')
setClass('connectionDefinition', contains = 'ConnectionDefinitionType')
setClass('connectionDefinition', contains = 'ConnectionDefinitionType')


#####  inst/xsd/eml-spatialReference.xsd  ####


setClass('lengthUnits', contains = 'character')
setClass('angleUnits', contains = 'character')
setClass('ListOfaltitudeResolution', contains = 'list')
setClass('ListOfdepthResolution', contains = 'list')
setClass('ListOfparameter', contains = 'list')
setClass('ListOfhorizCoordSysDef', contains = 'list')
setClass('vertCoordSys', slots = c('altitudeSysDef' = 'character', 'depthSysDef' = 'character'), contains = c('eml-2.1.1'))
setClass('altitudeSysDef', slots = c('altitudeDatumName' = 'character', 'altitudeResolution' = 'ListOfaltitudeResolution', 'altitudeDistanceUnits' = 'character', 'altitudeEncodingMethod' = 'character'), contains = c('eml-2.1.1'))
setClass('depthSysDef', slots = c('depthDatumName' = 'character', 'depthResolution' = 'ListOfdepthResolution', 'depthDistanceUnits' = 'character', 'depthEncodingMethod' = 'character'), contains = c('eml-2.1.1'))
setClass('datum', slots = c('name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('spheroid', slots = c('name' = 'xml_attribute', 'semiAxisMajor' = 'xml_attribute', 'denomFlatRatio' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('primeMeridian', slots = c('name' = 'xml_attribute', 'longitude' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('unit', slots = c('name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('projCoordSys', slots = c('geogCoordSys' = 'geogCoordSysType', 'projection' = 'projection'), contains = c('eml-2.1.1'))
setClass('projection', slots = c('parameter' = 'ListOfparameter', 'unit' = 'character', 'name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('parameter', slots = c('name' = 'xml_attribute', 'description' = 'xml_attribute', 'value' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('unit', slots = c('name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('projectionList', slots = c('horizCoordSysDef' = 'ListOfhorizCoordSysDef'), contains = c('eml-2.1.1'))
setClass('SpatialReferenceType', slots = c('horizCoordSysName' = 'character', 'horizCoordSysDef' = 'horizCoordSysType', 'vertCoordSys' = 'vertCoordSys', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('geogCoordSysType', slots = c('datum' = 'character', 'spheroid' = 'character', 'primeMeridian' = 'character', 'unit' = 'character', 'name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('horizCoordSysType', slots = c('geogCoordSys' = 'geogCoordSysType', 'projCoordSys' = 'projCoordSys', 'name' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('horizCoordSysDef', contains = 'horizCoordSysType')
setClass('altitudeResolution', contains = 'character')
setClass('depthResolution', contains = 'character')
setClass('geogCoordSys', contains = 'geogCoordSysType')
setClass('geogCoordSys', contains = 'geogCoordSysType')
setClass('horizCoordSysDef', contains = 'horizCoordSysType')
setClass('spatialReference', contains = 'SpatialReferenceType')


#####  inst/xsd/eml-access.xsd  ####


setClass('ListOfprincipal', contains = 'list')
setClass('ListOfpermission', contains = 'list')
setClass('AccessType', slots = c('allow' = 'AccessRule', 'deny' = 'AccessRule', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute', 'order' = 'xml_attribute', 'authSystem' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('AccessRule', slots = c('principal' = 'ListOfprincipal', 'permission' = 'ListOfpermission'), contains = c('eml-2.1.1'))
setClass('access', contains = 'AccessType')
setClass('allow', contains = 'AccessRule')
setClass('deny', contains = 'AccessRule')
setClass('principal', contains = 'character')


#####  inst/xsd/eml-constraint.xsd  ####


setClass('CardinalityChildOccurancesType', contains = 'character')
setClass('ListOfattributeReference', contains = 'list')
setClass('primaryKey', slots = c('key' = 'character'), contains = c('ConstraintBaseGroup', 'eml-2.1.1'))
setClass('key', slots = c('attributeReference' = 'ListOfattributeReference'), contains = c('eml-2.1.1'))
setClass('uniqueKey', slots = c('key' = 'character'), contains = c('ConstraintBaseGroup', 'eml-2.1.1'))
setClass('key', slots = c('attributeReference' = 'ListOfattributeReference'), contains = c('eml-2.1.1'))
setClass('checkConstraint', slots = c('checkCondition' = 'character', 'language' = 'xml_attribute'), contains = c('ConstraintBaseGroup', 'eml-2.1.1'))
setClass('foreignKey', contains = c('eml-2.1.1'))

setClass('referencedKey', slots = c('attributeReference' = 'ListOfattributeReference'), contains = c('eml-2.1.1'))
setClass('notNullConstraint', slots = c('key' = 'character'), contains = c('ConstraintBaseGroup', 'eml-2.1.1'))
setClass('key', slots = c('attributeReference' = 'ListOfattributeReference'), contains = c('eml-2.1.1'))
setClass('key', slots = c('attributeReference' = 'ListOfattributeReference'), contains = c('eml-2.1.1'))
setClass('cardinality', slots = c('parentOccurences' = 'character', 'childOccurences' = 'CardinalityChildOccurancesType'), contains = c('eml-2.1.1'))
setClass('ConstraintBaseGroup', slots = c('constraintName' = 'character', 'constraintDescription' = 'character'), contains = c('eml-2.1.1'))
setClass('ForeignKeyGroup', slots = c('key' = 'key', 'entityReference' = 'character', 'relationshipType' = 'character', 'cardinality' = 'cardinality'), contains = c('ConstraintBaseGroup', 'eml-2.1.1'))
setClass('ConstraintType', slots = c('primaryKey' = 'character', 'uniqueKey' = 'character', 'checkConstraint' = 'character', 'foreignKey' = 'character', 'joinCondition' = 'character', 'notNullConstraint' = 'character', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('joinCondition', slots = c('referencedKey' = 'character'), contains = c('ForeignKeyGroup', 'eml-2.1.1'))
setClass('joinCondition', slots = c('referencedKey' = 'character'), contains = c('ForeignKeyGroup', 'eml-2.1.1'))
setClass('joinCondition', slots = c('referencedKey' = 'character'), contains = c('ForeignKeyGroup', 'eml-2.1.1'))
setClass('joinCondition', slots = c('referencedKey' = 'character'), contains = c('ForeignKeyGroup', 'eml-2.1.1'))
setClass('joinCondition', slots = c('referencedKey' = 'character'), contains = c('ForeignKeyGroup', 'eml-2.1.1'))
setClass('childOccurences', contains = 'CardinalityChildOccurancesType')


#####  inst/xsd/eml-literature.xsd  ####


setClass('ListOfcontact', contains = 'list')
setClass('ListOfeditor', contains = 'list')
setClass('ListOfinstitution', contains = 'list')
setClass('ListOfrecipient', contains = 'list')
setClass('ListOfgeographicCoverage', contains = 'list')
setClass('ListOfpublicationPlace', contains = 'list')
setClass('ListOfperformer', contains = 'list')
setClass('CitationType', slots = c('contact' = 'ListOfcontact', 'article' = 'Article', 'book' = 'Book', 'chapter' = 'Chapter', 'editedBook' = 'Book', 'manuscript' = 'Manuscript', 'report' = 'Report', 'thesis' = 'Thesis', 'conferenceProceedings' = 'ConferenceProceedings', 'personalCommunication' = 'PersonalCommunication', 'map' = 'Map', 'generic' = 'Generic', 'audioVisual' = 'AudioVisual', 'presentation' = 'Presentation', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ResourceGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('Article', slots = c('journal' = 'character', 'volume' = 'character', 'issue' = 'character', 'pageRange' = 'character', 'publisher' = 'ResponsibleParty', 'publicationPlace' = 'character', 'ISSN' = 'character'), contains = c('eml-2.1.1'))
setClass('Book', slots = c('publisher' = 'ResponsibleParty', 'publicationPlace' = 'character', 'edition' = 'character', 'volume' = 'character', 'numberOfVolumes' = 'character', 'totalPages' = 'character', 'totalFigures' = 'character', 'totalTables' = 'character', 'ISBN' = 'character'), contains = c('eml-2.1.1'))
setClass('Chapter', slots = c('chapterNumber' = 'character', 'editor' = 'ListOfeditor', 'bookTitle' = 'character', 'pageRange' = 'character'), contains = c('Book', 'eml-2.1.1'))
setClass('ConferenceProceedings', slots = c('conferenceName' = 'character', 'conferenceDate' = 'character', 'conferenceLocation' = 'Address'), contains = c('Chapter', 'eml-2.1.1'))
setClass('Manuscript', slots = c('institution' = 'ListOfinstitution', 'totalPages' = 'character'), contains = c('eml-2.1.1'))
setClass('Report', slots = c('reportNumber' = 'character', 'publisher' = 'ResponsibleParty', 'publicationPlace' = 'character', 'totalPages' = 'character'), contains = c('eml-2.1.1'))
setClass('PersonalCommunication', slots = c('publisher' = 'ResponsibleParty', 'publicationPlace' = 'character', 'communicationType' = 'character', 'recipient' = 'ListOfrecipient'), contains = c('eml-2.1.1'))
setClass('Map', slots = c('publisher' = 'ResponsibleParty', 'edition' = 'character', 'geographicCoverage' = 'ListOfgeographicCoverage', 'scale' = 'character'), contains = c('eml-2.1.1'))
setClass('AudioVisual', slots = c('publisher' = 'ResponsibleParty', 'publicationPlace' = 'ListOfpublicationPlace', 'performer' = 'ListOfperformer', 'ISBN' = 'character'), contains = c('eml-2.1.1'))
setClass('Generic', slots = c('publisher' = 'ResponsibleParty', 'publicationPlace' = 'character', 'referenceType' = 'character', 'volume' = 'character', 'numberOfVolumes' = 'character', 'totalPages' = 'character', 'totalFigures' = 'character', 'totalTables' = 'character', 'edition' = 'character', 'originalPublication' = 'character', 'reprintEdition' = 'character', 'reviewedItem' = 'character', 'ISBN' = 'character', 'ISSN' = 'character'), contains = c('eml-2.1.1'))
setClass('Thesis', slots = c('degree' = 'character', 'institution' = 'ResponsibleParty', 'totalPages' = 'character'), contains = c('eml-2.1.1'))
setClass('Presentation', slots = c('conferenceName' = 'character', 'conferenceDate' = 'character', 'conferenceLocation' = 'Address'), contains = c('eml-2.1.1'))
setClass('citation', contains = 'CitationType')
setClass('contact', contains = 'ResponsibleParty')
setClass('article', contains = 'Article')
setClass('book', contains = 'Book')
setClass('chapter', contains = 'Chapter')
setClass('editedBook', contains = 'Book')
setClass('manuscript', contains = 'Manuscript')
setClass('report', contains = 'Report')
setClass('thesis', contains = 'Thesis')
setClass('conferenceProceedings', contains = 'ConferenceProceedings')
setClass('personalCommunication', contains = 'PersonalCommunication')
setClass('map', contains = 'Map')
setClass('generic', contains = 'Generic')
setClass('audioVisual', contains = 'AudioVisual')
setClass('presentation', contains = 'Presentation')
setClass('publisher', contains = 'ResponsibleParty')
setClass('publisher', contains = 'ResponsibleParty')
setClass('editor', contains = 'ResponsibleParty')
setClass('conferenceLocation', contains = 'Address')
setClass('institution', contains = 'ResponsibleParty')
setClass('publisher', contains = 'ResponsibleParty')
setClass('publisher', contains = 'ResponsibleParty')
setClass('recipient', contains = 'ResponsibleParty')
setClass('publisher', contains = 'ResponsibleParty')

setClass('publisher', contains = 'ResponsibleParty')
setClass('publicationPlace', contains = 'character')
setClass('performer', contains = 'ResponsibleParty')
setClass('publisher', contains = 'ResponsibleParty')
setClass('institution', contains = 'ResponsibleParty')
setClass('conferenceLocation', contains = 'Address')


#####  inst/xsd/eml-coverage.xsd  ####


setClass('GRingType', contains = 'character')
setClass('ListOfsingleDateTime', contains = 'list')
setClass('ListOftimeScaleCitation', contains = 'list')
setClass('ListOfdatasetGPolygon', contains = 'list')
setClass('ListOfgRingPoint', contains = 'list')
setClass('ListOfdatasetGPolygonExclusionGRing', contains = 'list')
setClass('ListOfclassificationSystem', contains = 'list')
setClass('ListOfidentificationReference', contains = 'list')
setClass('ListOfidentifierName', contains = 'list')
setClass('ListOfvouchers', contains = 'list')
setClass('ListOforiginator', contains = 'list')
setClass('ListOftaxonomicClassification', contains = 'list')
setClass('ListOfcommonName', contains = 'list')


setClass('rangeOfDates', slots = c('beginDate' = 'SingleDateTimeType', 'endDate' = 'SingleDateTimeType'), contains = c('eml-2.1.1'))
setClass('alternativeTimeScale', slots = c('timeScaleName' = 'character', 'timeScaleAgeEstimate' = 'character', 'timeScaleAgeUncertainty' = 'character', 'timeScaleAgeExplanation' = 'character', 'timeScaleCitation' = 'ListOftimeScaleCitation'), contains = c('eml-2.1.1'))
setClass('boundingCoordinates', slots = c('westBoundingCoordinate' = 'character', 'eastBoundingCoordinate' = 'character', 'northBoundingCoordinate' = 'character', 'southBoundingCoordinate' = 'character', 'boundingAltitudes' = 'character'), contains = c('eml-2.1.1'))
setClass('boundingAltitudes', slots = c('altitudeMinimum' = 'xs:decimal', 'altitudeMaximum' = 'xs:decimal', 'altitudeUnits' = 'LengthUnitType'), contains = c('eml-2.1.1'))
setClass('datasetGPolygon', slots = c('datasetGPolygonOuterGRing' = 'character', 'datasetGPolygonExclusionGRing' = 'ListOfdatasetGPolygonExclusionGRing'), contains = c('eml-2.1.1'))
setClass('datasetGPolygonOuterGRing', slots = c('gRingPoint' = 'ListOfgRingPoint', 'gRing' = 'GRingType'), contains = c('eml-2.1.1'))
setClass('datasetGPolygonExclusionGRing', slots = c('gRingPoint' = 'ListOfgRingPoint', 'gRing' = 'GRingType'), contains = c('eml-2.1.1'))
setClass('taxonomicSystem', slots = c('classificationSystem' = 'ListOfclassificationSystem', 'identificationReference' = 'ListOfidentificationReference', 'identifierName' = 'ListOfidentifierName', 'taxonomicProcedures' = 'character', 'taxonomicCompleteness' = 'character', 'vouchers' = 'ListOfvouchers'), contains = c('eml-2.1.1'))
setClass('classificationSystem', slots = c('classificationSystemCitation' = 'CitationType', 'classificationSystemModifications' = 'character'), contains = c('eml-2.1.1'))
setClass('vouchers', slots = c('specimen' = 'character', 'repository' = 'repository'), contains = c('eml-2.1.1'))
setClass('repository', slots = c('originator' = 'ListOforiginator'), contains = c('eml-2.1.1'))
setClass('Coverage', slots = c('geographicCoverage' = 'GeographicCoverage', 'temporalCoverage' = 'TemporalCoverage', 'taxonomicCoverage' = 'TaxonomicCoverage', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('TemporalCoverage', slots = c('singleDateTime' = 'ListOfsingleDateTime', 'rangeOfDates' = 'rangeOfDates', 'id' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('SingleDateTimeType', slots = c('calendarDate' = 'yearDate', 'time' = 'xs:time', 'alternativeTimeScale' = 'alternativeTimeScale'), contains = c('eml-2.1.1'))
setClass('GeographicCoverage', slots = c('geographicDescription' = 'character', 'boundingCoordinates' = 'boundingCoordinates', 'datasetGPolygon' = 'ListOfdatasetGPolygon', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('GRingPointType', slots = c('gRingLatitude' = 'character', 'gRingLongitude' = 'character'), contains = c('eml-2.1.1'))
setClass('TaxonomicCoverage', slots = c('taxonomicSystem' = 'taxonomicSystem', 'generalTaxonomicCoverage' = 'character', 'taxonomicClassification' = 'ListOftaxonomicClassification', 'id' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('TaxonomicClassificationType', slots = c('taxonRankName' = 'character', 'taxonRankValue' = 'character', 'commonName' = 'ListOfcommonName', 'taxonomicClassification' = 'ListOftaxonomicClassification'), contains = c('eml-2.1.1'))

setClass('singleDateTime', contains = 'SingleDateTimeType')
setClass('beginDate', contains = 'SingleDateTimeType')
setClass('endDate', contains = 'SingleDateTimeType')
setClass('calendarDate', contains = 'yearDate')
setClass('time', contains = 'xs:time')
setClass('timeScaleCitation', contains = 'CitationType')
setClass('altitudeMinimum', contains = 'xs:decimal')
setClass('altitudeMaximum', contains = 'xs:decimal')
setClass('altitudeUnits', contains = 'LengthUnitType')
setClass('gRingPoint', contains = 'GRingPointType')
setClass('gRing', contains = 'GRingType')
setClass('gRingPoint', contains = 'GRingPointType')
setClass('gRing', contains = 'GRingType')
setClass('classificationSystemCitation', contains = 'CitationType')
setClass('identificationReference', contains = 'CitationType')
setClass('identifierName', contains = 'ResponsibleParty')
setClass('originator', contains = 'ResponsibleParty')
setClass('taxonomicClassification', contains = 'TaxonomicClassificationType')
setClass('commonName', contains = 'character')
setClass('taxonomicClassification', contains = 'TaxonomicClassificationType')


#####  inst/xsd/eml-physical.xsd  ####


setClass('ListOfauthentication', contains = 'list')
setClass('ListOfrecordDelimiter', contains = 'list')
setClass('ListOfphysicalLineDelimiter', contains = 'list')
setClass('ListOffieldDelimiter', contains = 'list')
setClass('ListOfquoteCharacter', contains = 'list')
setClass('ListOfliteralCharacter', contains = 'list')
setClass('ListOfdistribution', contains = 'list')
setClass('size', slots = c('unit' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('authentication', slots = c('method' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('dataFormat', slots = c('textFormat' = 'character', 'externallyDefinedFormat' = 'character', 'binaryRasterFormat' = 'character'), contains = c('eml-2.1.1'))
setClass('textFormat', slots = c('numHeaderLines' = 'xs:int', 'numFooterLines' = 'xs:int', 'recordDelimiter' = 'ListOfrecordDelimiter', 'physicalLineDelimiter' = 'ListOfphysicalLineDelimiter', 'numPhysicalLinesPerRecord' = 'xs:unsignedInt', 'maxRecordLength' = 'xs:unsignedLong', 'attributeOrientation' = 'character', 'simpleDelimited' = 'simpleDelimited', 'complex' = 'complex'), contains = c('eml-2.1.1'))
setClass('simpleDelimited', slots = c('fieldDelimiter' = 'ListOffieldDelimiter', 'collapseDelimiters' = 'character', 'quoteCharacter' = 'ListOfquoteCharacter', 'literalCharacter' = 'ListOfliteralCharacter'), contains = c('eml-2.1.1'))
setClass('eml:complex', slots = c('textFixed' = 'character', 'textDelimited' = 'character'), contains = c('eml-2.1.1'))
setClass('textFixed', slots = c('fieldWidth' = 'xs:unsignedLong', 'lineNumber' = 'xs:unsignedLong', 'fieldStartColumn' = 'xs:long'), contains = c('eml-2.1.1'))
setClass('textDelimited', slots = c('fieldDelimiter' = 'xs:string', 'collapseDelimiters' = 'character', 'lineNumber' = 'xs:unsignedLong', 'quoteCharacter' = 'ListOfquoteCharacter', 'literalCharacter' = 'ListOfliteralCharacter'), contains = c('eml-2.1.1'))
setClass('externallyDefinedFormat', slots = c('formatName' = 'character', 'formatVersion' = 'character', 'citation' = 'CitationType'), contains = c('eml-2.1.1'))
setClass('binaryRasterFormat', slots = c('rowColumnOrientation' = 'character', 'multiBand' = 'multiBand', 'nbits' = 'xs:int', 'byteorder' = 'character', 'skipbytes' = 'character', 'bandrowbytes' = 'character', 'totalrowbytes' = 'character', 'bandgapbytes' = 'character'), contains = c('eml-2.1.1'))
setClass('multiBand', slots = c('nbands' = 'xs:int', 'layout' = 'character'), contains = c('eml-2.1.1'))
setClass('PhysicalType', slots = c('objectName' = 'character', 'size' = 'xs:string', 'authentication' = 'ListOfauthentication', 'compressionMethod' = 'character', 'encodingMethod' = 'character', 'characterEncoding' = 'character', 'dataFormat' = 'dataFormat', 'distribution' = 'ListOfdistribution', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('PhysicalDistributionType', slots = c('online' = 'PhysicalOnlineType', 'offline' = 'OfflineType', 'inline' = 'InlineType', 'access' = 'AccessType', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('PhysicalOnlineType', slots = c('onlineDescription' = 'character', 'url' = 'UrlType', 'connection' = 'ConnectionType'), contains = c('eml-2.1.1'))
setClass('physical', contains = 'PhysicalType')
setClass('numHeaderLines', contains = 'xs:int')
setClass('numFooterLines', contains = 'xs:int')
setClass('recordDelimiter', contains = 'xs:string')
setClass('physicalLineDelimiter', contains = 'xs:string')
setClass('numPhysicalLinesPerRecord', contains = 'xs:unsignedInt')
setClass('maxRecordLength', contains = 'xs:unsignedLong')
setClass('fieldDelimiter', contains = 'xs:string')
setClass('quoteCharacter', contains = 'character')
setClass('literalCharacter', contains = 'character')
setClass('fieldWidth', contains = 'xs:unsignedLong')
setClass('lineNumber', contains = 'xs:unsignedLong')
setClass('fieldStartColumn', contains = 'xs:long')
setClass('fieldDelimiter', contains = 'xs:string')
setClass('lineNumber', contains = 'xs:unsignedLong')
setClass('quoteCharacter', contains = 'character')
setClass('literalCharacter', contains = 'character')
setClass('citation', contains = 'CitationType')
setClass('nbands', contains = 'xs:int')
setClass('nbits', contains = 'xs:int')
setClass('distribution', contains = 'PhysicalDistributionType')
setClass('online', contains = 'PhysicalOnlineType')
setClass('offline', contains = 'OfflineType')
setClass('inline', contains = 'InlineType')
setClass('access', contains = 'AccessType')
setClass('url', contains = 'UrlType')
setClass('connection', contains = 'ConnectionType')


#####  inst/xsd/eml-project.xsd  ####


setClass('DescriptorType', contains = 'character')
setClass('ListOftitle', contains = 'list')
setClass('ListOfpersonnel', contains = 'list')
setClass('ListOfdescriptorValue', contains = 'list')
setClass('ListOfcitation', contains = 'list')
setClass('ListOfrelatedProject', contains = 'list')
setClass('personnel', slots = c('role' = 'RoleType'), contains = c('ResponsibleParty', 'eml-2.1.1'))
setClass('studyAreaDescription', slots = c('descriptor' = 'descriptor', 'citation' = 'CitationType', 'coverage' = 'Coverage'), contains = c('eml-2.1.1'))
setClass('descriptor', slots = c('descriptorValue' = 'ListOfdescriptorValue', 'citation' = 'ListOfcitation', 'name' = 'xml_attribute', 'citableClassificationSystem' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('descriptorValue', slots = c('name_or_id' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('designDescription', slots = c('description' = 'TextType', 'citation' = 'CitationType'), contains = c('eml-2.1.1'))
setClass('ResearchProjectType', slots = c('title' = 'ListOftitle', 'personnel' = 'ListOfpersonnel', 'abstract' = 'TextType', 'funding' = 'TextType', 'studyAreaDescription' = 'studyAreaDescription', 'designDescription' = 'designDescription', 'relatedProject' = 'ListOfrelatedProject', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('researchProject', contains = 'ResearchProjectType')
setClass('title', contains = 'character')
setClass('role', contains = 'RoleType')
setClass('abstract', contains = 'TextType')
setClass('funding', contains = 'TextType')
setClass('citation', contains = 'CitationType')
setClass('citation', contains = 'CitationType')

setClass('description', contains = 'TextType')
setClass('citation', contains = 'CitationType')
setClass('relatedProject', contains = 'ResearchProjectType')


#####  inst/xsd/eml-software.xsd  ####


setClass('Action', contains = 'character')
setClass('ListOfimplementation', contains = 'list')
setClass('ListOfdistribution', contains = 'list')
setClass('ListOflanguage', contains = 'list')
setClass('ListOfoperatingSystem', contains = 'list')
setClass('ListOfmachineProcessor', contains = 'list')
setClass('ListOfprogrammingLanguage', contains = 'list')
setClass('ListOfdependency', contains = 'list')
setClass('implementation', slots = c('distribution' = 'ListOfdistribution', 'size' = 'character', 'language' = 'ListOflanguage', 'operatingSystem' = 'ListOfoperatingSystem', 'machineProcessor' = 'ListOfmachineProcessor', 'virtualMachine' = 'character', 'diskUsage' = 'character', 'runtimeMemoryUsage' = 'character', 'programmingLanguage' = 'ListOfprogrammingLanguage', 'checksum' = 'character', 'dependency' = 'ListOfdependency'), contains = c('eml-2.1.1'))
setClass('eml:language', slots = c('LanguageValue' = 'character', 'LanguageCodeStandard' = 'character'), contains = c('eml-2.1.1'))
setClass('dependency', slots = c('action' = 'Action', 'software' = 'character'), contains = c('eml-2.1.1'))
setClass('SoftwareType', slots = c('implementation' = 'ListOfimplementation', 'dependency' = 'ListOfdependency', 'licenseURL' = 'character', 'license' = 'character', 'version' = 'character', 'project' = 'ResearchProjectType', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ResourceGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('software', contains = 'SoftwareType')
setClass('distribution', contains = 'PhysicalDistributionType')
setClass('operatingSystem', contains = 'character')
setClass('machineProcessor', contains = 'character')
setClass('programmingLanguage', contains = 'character')
setClass('project', contains = 'ResearchProjectType')
setClass('action', contains = 'Action')


#####  inst/xsd/eml-protocol.xsd  ####


setClass('ListOfproceduralStep', contains = 'list')
setClass('ProtocolType', slots = c('proceduralStep' = 'ListOfproceduralStep', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ResourceGroup', 'ReferencesGroup', 'eml-2.1.1'))




#####  inst/xsd/eml-methods.xsd  ####


setClass('ListOfmethodStep', contains = 'list')
setClass('ListOfdataSource', contains = 'list')
setClass('ListOfcitation', contains = 'list')
setClass('ListOfqualityControl', contains = 'list')
setClass('ListOfinstrumentation', contains = 'list')
setClass('ListOfsoftware', contains = 'list')
setClass('ListOfsubStep', contains = 'list')

setClass('sampling', slots = c('studyExtent' = 'studyExtent', 'samplingDescription' = 'TextType', 'spatialSamplingUnits' = 'spatialSamplingUnits', 'citation' = 'ListOfcitation'), contains = c('eml-2.1.1'))
setClass('studyExtent', slots = c('coverage' = 'Coverage', 'description' = 'TextType'), contains = c('eml-2.1.1'))
setClass('spatialSamplingUnits', slots = c('referencedEntityId' = 'character', 'coverage' = 'GeographicCoverage'), contains = c('eml-2.1.1'))
setClass('MethodsType', slots = c('methodStep' = 'ListOfmethodStep', 'sampling' = 'sampling', 'qualityControl' = 'ListOfqualityControl'), contains = c('eml-2.1.1'))
setClass('ProcedureStepType', slots = c('description' = 'TextType', 'citation' = 'CitationType', 'protocol' = 'ProtocolType', 'instrumentation' = 'ListOfinstrumentation', 'software' = 'ListOfsoftware', 'subStep' = 'ListOfsubStep'), contains = c('eml-2.1.1'))
setClass('methods', contains = 'MethodsType')


setClass('description', contains = 'TextType')
setClass('samplingDescription', contains = 'TextType')

setClass('citation', contains = 'CitationType')
setClass('qualityControl', contains = 'ProcedureStepType')
setClass('description', contains = 'TextType')
setClass('citation', contains = 'CitationType')

setClass('instrumentation', contains = 'character')
setClass('software', contains = 'SoftwareType')
setClass('subStep', contains = 'ProcedureStepType')


#####  inst/xsd/eml-attribute.xsd  ####


setClass('NumberType', contains = 'character')
setClass('ListOfattribute', contains = 'list')
setClass('ListOfattributeLabel', contains = 'list')
setClass('ListOfstorageType', contains = 'list')
setClass('ListOfmissingValueCode', contains = 'list')
setClass('ListOfquantitativeAttributeAccuracyAssessment', contains = 'list')
setClass('ListOfcodeDefinition', contains = 'list')
setClass('ListOfpattern', contains = 'list')
setClass('ListOfbounds', contains = 'list')
setClass('storageType', slots = c('typeSystem' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('measurementScale', slots = c('nominal' = 'character', 'ordinal' = 'character', 'interval' = 'character', 'ratio' = 'character', 'dateTime' = 'character'), contains = c('eml-2.1.1'))
setClass('nominal', slots = c('nonNumericDomain' = 'NonNumericDomainType'), contains = c('eml-2.1.1'))
setClass('ordinal', slots = c('nonNumericDomain' = 'NonNumericDomainType'), contains = c('eml-2.1.1'))
setClass('interval', slots = c('unit' = 'UnitType', 'precision' = 'PrecisionType', 'numericDomain' = 'NumericDomainType'), contains = c('eml-2.1.1'))
setClass('ratio', slots = c('unit' = 'UnitType', 'precision' = 'PrecisionType', 'numericDomain' = 'NumericDomainType'), contains = c('eml-2.1.1'))
setClass('dateTime', slots = c('formatString' = 'character', 'dateTimePrecision' = 'character', 'dateTimeDomain' = 'DateTimeDomainType'), contains = c('eml-2.1.1'))
setClass('missingValueCode', slots = c('code' = 'character', 'codeExplanation' = 'character'), contains = c('eml-2.1.1'))
setClass('quantitativeAttributeAccuracyAssessment', slots = c('attributeAccuracyValue' = 'character', 'attributeAccuracyExplanation' = 'character'), contains = c('eml-2.1.1'))
setClass('enumeratedDomain', slots = c('codeDefinition' = 'ListOfcodeDefinition', 'externalCodeSet' = 'character', 'entityCodeList' = 'character', 'enforced' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('codeDefinition', slots = c('code' = 'character', 'definition' = 'character', 'source' = 'character', 'order' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('externalCodeSet', slots = c('codesetName' = 'character', 'citation' = 'CitationType', 'codesetURL' = 'xs:anyURI'), contains = c('eml-2.1.1'))
setClass('entityCodeList', slots = c('entityReference' = 'character', 'valueAttributeReference' = 'character', 'definitionAttributeReference' = 'character', 'orderAttributeReference' = 'character'), contains = c('eml-2.1.1'))
setClass('textDomain', slots = c('definition' = 'character', 'pattern' = 'ListOfpattern', 'source' = 'character'), contains = c('eml-2.1.1'))
setClass('bounds', slots = c('minimum' = 'character', 'maximum' = 'character'), contains = c('eml-2.1.1'))
setClass('minimum', slots = c('exclusive' = 'xml_attribute'), contains = c('xs:float', 'eml-2.1.1'))
setClass('maximum', slots = c('exclusive' = 'xml_attribute'), contains = c('xs:float', 'eml-2.1.1'))
setClass('bounds', slots = c('minimum' = 'character', 'maximum' = 'character'), contains = c('eml-2.1.1'))
setClass('minimum', slots = c('exclusive' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('maximum', slots = c('exclusive' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('BoundsGroup', slots = c('bounds' = 'ListOfbounds'), contains = c('eml-2.1.1'))
setClass('BoundsDateGroup', slots = c('bounds' = 'ListOfbounds'), contains = c('eml-2.1.1'))
setClass('AttributeListType', slots = c('attribute' = 'ListOfattribute', 'id' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('AttributeType', slots = c('attributeName' = 'character', 'attributeLabel' = 'ListOfattributeLabel', 'attributeDefinition' = 'character', 'storageType' = 'ListOfstorageType', 'measurementScale' = 'measurementScale', 'missingValueCode' = 'ListOfmissingValueCode', 'accuracy' = 'Accuracy', 'coverage' = 'Coverage', 'methods' = 'MethodsType', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('Accuracy', slots = c('attributeAccuracyReport' = 'character', 'quantitativeAttributeAccuracyAssessment' = 'ListOfquantitativeAttributeAccuracyAssessment'), contains = c('eml-2.1.1'))
setClass('UnitType', slots = c('standardUnit' = 'StandardUnitDictionary', 'customUnit' = 'character'), contains = c('eml-2.1.1'))
setClass('PrecisionType', contains = c('xs:float', 'eml-2.1.1'))
setClass('NonNumericDomainType', slots = c('enumeratedDomain' = 'character', 'textDomain' = 'character', 'id' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
setClass('NumericDomainType', slots = c('numberType' = 'NumberType', 'id' = 'xml_attribute'), contains = c('BoundsGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('DateTimeDomainType', slots = c('id' = 'xml_attribute'), contains = c('BoundsDateGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('attribute', contains = 'AttributeType')
setClass('attribute', contains = 'AttributeType')
setClass('attributeLabel', contains = 'character')
setClass('nonNumericDomain', contains = 'NonNumericDomainType')
setClass('nonNumericDomain', contains = 'NonNumericDomainType')
setClass('unit', contains = 'UnitType')
setClass('precision', contains = 'PrecisionType')
setClass('numericDomain', contains = 'NumericDomainType')
setClass('unit', contains = 'UnitType')
setClass('precision', contains = 'PrecisionType')
setClass('numericDomain', contains = 'NumericDomainType')
setClass('dateTimeDomain', contains = 'DateTimeDomainType')
setClass('accuracy', contains = 'Accuracy')

setClass('methods', contains = 'MethodsType')
setClass('attributeList', contains = 'AttributeListType')
setClass('standardUnit', contains = 'StandardUnitDictionary')
setClass('citation', contains = 'CitationType')
setClass('codesetURL', contains = 'xs:anyURI')
setClass('pattern', contains = 'character')
setClass('numberType', contains = 'NumberType')


#####  inst/xsd/eml-entity.xsd  ####


setClass('ListOfconstraint', contains = 'list')
setClass('ListOfalternateIdentifier', contains = 'list')
setClass('ListOfphysical', contains = 'list')
setClass('ListOfadditionalInfo', contains = 'list')
setClass('alternateIdentifier', slots = c('system' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('EntityGroup', slots = c('alternateIdentifier' = 'ListOfalternateIdentifier', 'entityName' = 'character', 'entityDescription' = 'character', 'physical' = 'ListOfphysical', 'coverage' = 'Coverage', 'methods' = 'MethodsType', 'additionalInfo' = 'ListOfadditionalInfo'), contains = c('eml-2.1.1'))
setClass('OtherEntityType', slots = c('attributeList' = 'AttributeListType', 'constraint' = 'ListOfconstraint', 'entityType' = 'character', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('EntityGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('otherEntity', contains = 'OtherEntityType')
setClass('attributeList', contains = 'AttributeListType')
setClass('constraint', contains = 'ConstraintType')
setClass('physical', contains = 'PhysicalType')

setClass('methods', contains = 'MethodsType')
setClass('additionalInfo', contains = 'TextType')


#####  inst/xsd/eml-dataTable.xsd  ####


setClass('ListOfconstraint', contains = 'list')
setClass('DataTableType', slots = c('attributeList' = 'AttributeListType', 'constraint' = 'ListOfconstraint', 'caseSensitive' = 'character', 'numberOfRecords' = 'character', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('EntityGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('dataTable', contains = 'DataTableType')
setClass('attributeList', contains = 'AttributeListType')
setClass('constraint', contains = 'ConstraintType')


#####  inst/xsd/eml-view.xsd  ####


setClass('ListOfconstraint', contains = 'list')
setClass('ViewType', slots = c('attributeList' = 'AttributeListType', 'constraint' = 'ListOfconstraint', 'queryStatement' = 'character', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('EntityGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('view', contains = 'ViewType')
setClass('attributeList', contains = 'AttributeListType')
setClass('constraint', contains = 'ConstraintType')


#####  inst/xsd/eml-storedProcedure.xsd  ####


setClass('ListOfconstraint', contains = 'list')
setClass('ListOfparameter', contains = 'list')
setClass('StoredProcedureType', slots = c('attributeList' = 'AttributeListType', 'constraint' = 'ListOfconstraint', 'parameter' = 'ListOfparameter', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('EntityGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('ParameterType', slots = c('name' = 'character', 'domainDescription' = 'character', 'required' = 'xs:boolean', 'repeats' = 'xs:boolean'), contains = c('eml-2.1.1'))
setClass('storedProcedure', contains = 'StoredProcedureType')
setClass('attributeList', contains = 'AttributeListType')
setClass('constraint', contains = 'ConstraintType')
setClass('parameter', contains = 'ParameterType')
setClass('required', contains = 'xs:boolean')
setClass('repeats', contains = 'xs:boolean')


#####  inst/xsd/eml-spatialVector.xsd  ####


setClass('GeometryType', contains = 'character')
setClass('TopologyLevel', contains = 'character')
setClass('ListOfconstraint', contains = 'list')
setClass('ListOfgeometry', contains = 'list')
setClass('ListOfquantitativeAccuracyReport', contains = 'list')
setClass('quantitativeAccuracyReport', slots = c('quantitativeAccuracyValue' = 'character', 'quantitativeAccuracyMethod' = 'character'), contains = c('eml-2.1.1'))
setClass('SpatialVectorType', slots = c('attributeList' = 'AttributeListType', 'constraint' = 'ListOfconstraint', 'geometry' = 'ListOfgeometry', 'geometricObjectCount' = 'character', 'topologyLevel' = 'TopologyLevel', 'spatialReference' = 'SpatialReferenceType', 'horizontalAccuracy' = 'DataQuality', 'verticalAccuracy' = 'DataQuality', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('EntityGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('DataQuality', slots = c('accuracyReport' = 'character', 'quantitativeAccuracyReport' = 'ListOfquantitativeAccuracyReport'), contains = c('eml-2.1.1'))
setClass('spatialVector', contains = 'SpatialVectorType')
setClass('attributeList', contains = 'AttributeListType')
setClass('constraint', contains = 'ConstraintType')
setClass('geometry', contains = 'GeometryType')
setClass('topologyLevel', contains = 'TopologyLevel')
setClass('spatialReference', contains = 'SpatialReferenceType')
setClass('horizontalAccuracy', contains = 'DataQuality')
setClass('verticalAccuracy', contains = 'DataQuality')


#####  inst/xsd/eml-spatialRaster.xsd  ####


setClass('CellValueType', contains = 'character')
setClass('ImagingConditionCode', contains = 'character')
setClass('rasterOriginType', contains = 'character')
setClass('CellGeometryType', contains = 'character')
setClass('ListOfconstraint', contains = 'list')
setClass('ListOfcornerPoint', contains = 'list')
setClass('ListOfcontrolPoint', contains = 'list')
setClass('ListOfbandDescription', contains = 'list')
setClass('ListOfquantitativeAccuracyReport', contains = 'list')
setClass('georeferenceInfo', slots = c('cornerPoint' = 'ListOfcornerPoint', 'controlPoint' = 'ListOfcontrolPoint', 'bilinearFit' = 'character'), contains = c('eml-2.1.1'))
setClass('cornerPoint', slots = c('xCoordinate' = 'xs:float', 'yCoordinate' = 'xs:float', 'pointInPixel' = 'character', 'corner' = 'rasterOriginType'), contains = c('eml-2.1.1'))
setClass('controlPoint', slots = c('column' = 'xs:int', 'row' = 'xs:int', 'xCoordinate' = 'xs:float', 'yCoordinate' = 'xs:float', 'pointInPixel' = 'character'), contains = c('eml-2.1.1'))
setClass('bilinearFit', slots = c('xIntercept' = 'xs:float', 'xSlope' = 'xs:float', 'yIntercept' = 'xs:float', 'ySlope' = 'xs:float'), contains = c('eml-2.1.1'))
setClass('imageDescription', slots = c('illuminationElevationAngle' = 'xs:float', 'illuminationAzimuthAngle' = 'xs:float', 'imageOrientationAngle' = 'xs:float', 'imagingCondition' = 'ImagingConditionCode', 'imageQualityCode' = 'character', 'cloudCoverPercentage' = 'xs:float', 'preProcessingTypeCode' = 'character', 'compressionGenerationQuality' = 'xs:integer', 'triangulationIndicator' = 'xs:boolean', 'radiometricDataAvailability' = 'xs:boolean', 'cameraCalibrationInformationAvailability' = 'xs:boolean', 'filmDistortionInformationAvailability' = 'xs:boolean', 'lensDistortionInformationAvailability' = 'xs:boolean', 'bandDescription' = 'ListOfbandDescription'), contains = c('eml-2.1.1'))
setClass('quantitativeAccuracyReport', slots = c('quantitativeAccuracyValue' = 'character', 'quantitativeAccuracyMethod' = 'character'), contains = c('eml-2.1.1'))
setClass('SpatialRasterType', slots = c('attributeList' = 'AttributeListType', 'constraint' = 'ListOfconstraint', 'spatialReference' = 'SpatialReferenceType', 'georeferenceInfo' = 'georeferenceInfo', 'horizontalAccuracy' = 'DataQuality', 'verticalAccuracy' = 'DataQuality', 'cellSizeXDirection' = 'character', 'cellSizeYDirection' = 'character', 'numberOfBands' = 'character', 'rasterOrigin' = 'rasterOriginType', 'rows' = 'character', 'columns' = 'character', 'verticals' = 'character', 'cellGeometry' = 'CellGeometryType', 'toneGradation' = 'xs:integer', 'scaleFactor' = 'character', 'offset' = 'character', 'imageDescription' = 'imageDescription', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('EntityGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('BandType', slots = c('sequenceIdentifier' = 'character', 'highWavelength' = 'xs:float', 'lowWaveLength' = 'xs:float', 'waveLengthUnits' = 'lengthUnits', 'peakResponse' = 'character'), contains = c('eml-2.1.1'))
setClass('DataQuality', slots = c('accuracyReport' = 'character', 'quantitativeAccuracyReport' = 'ListOfquantitativeAccuracyReport'), contains = c('eml-2.1.1'))
setClass('spatialRaster', contains = 'SpatialRasterType')
setClass('attributeList', contains = 'AttributeListType')
setClass('constraint', contains = 'ConstraintType')
setClass('spatialReference', contains = 'SpatialReferenceType')
setClass('xCoordinate', contains = 'xs:float')
setClass('yCoordinate', contains = 'xs:float')
setClass('corner', contains = 'rasterOriginType')
setClass('column', contains = 'xs:int')
setClass('row', contains = 'xs:int')
setClass('xCoordinate', contains = 'xs:float')
setClass('yCoordinate', contains = 'xs:float')
setClass('xIntercept', contains = 'xs:float')
setClass('xSlope', contains = 'xs:float')
setClass('yIntercept', contains = 'xs:float')
setClass('ySlope', contains = 'xs:float')
setClass('horizontalAccuracy', contains = 'DataQuality')
setClass('verticalAccuracy', contains = 'DataQuality')
setClass('rasterOrigin', contains = 'rasterOriginType')
setClass('cellGeometry', contains = 'CellGeometryType')
setClass('toneGradation', contains = 'xs:integer')
setClass('illuminationElevationAngle', contains = 'xs:float')
setClass('illuminationAzimuthAngle', contains = 'xs:float')
setClass('imageOrientationAngle', contains = 'xs:float')
setClass('imagingCondition', contains = 'ImagingConditionCode')
setClass('cloudCoverPercentage', contains = 'xs:float')
setClass('compressionGenerationQuality', contains = 'xs:integer')
setClass('triangulationIndicator', contains = 'xs:boolean')
setClass('radiometricDataAvailability', contains = 'xs:boolean')
setClass('cameraCalibrationInformationAvailability', contains = 'xs:boolean')
setClass('filmDistortionInformationAvailability', contains = 'xs:boolean')
setClass('lensDistortionInformationAvailability', contains = 'xs:boolean')
setClass('bandDescription', contains = 'BandType')
setClass('highWavelength', contains = 'xs:float')
setClass('lowWaveLength', contains = 'xs:float')
setClass('waveLengthUnits', contains = 'lengthUnits')


#####  inst/xsd/eml-dataset.xsd  ####


setClass('MaintUpFreqType', contains = 'character')
setClass('ListOfcontact', contains = 'list')
setClass('ListOfchangeHistory', contains = 'list')
setClass('changeHistory', slots = c('changeScope' = 'character', 'oldValue' = 'character', 'changeDate' = 'xs:date', 'comment' = 'character'), contains = c('eml-2.1.1'))
setClass('DatasetType', slots = c('purpose' = 'TextType', 'maintenance' = 'MaintenanceType', 'contact' = 'ListOfcontact', 'publisher' = 'ResponsibleParty', 'pubPlace' = 'character', 'methods' = 'MethodsType', 'project' = 'ResearchProjectType', 'dataTable' = 'DataTableType', 'spatialRaster' = 'SpatialRasterType', 'spatialVector' = 'SpatialVectorType', 'storedProcedure' = 'StoredProcedureType', 'view' = 'ViewType', 'otherEntity' = 'OtherEntityType', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ResourceGroup', 'ReferencesGroup', 'eml-2.1.1'))
setClass('MaintenanceType', slots = c('description' = 'TextType', 'maintenanceUpdateFrequency' = 'MaintUpFreqType', 'changeHistory' = 'ListOfchangeHistory'), contains = c('eml-2.1.1'))
setClass('dataset', contains = 'DatasetType')
setClass('purpose', contains = 'TextType')
setClass('maintenance', contains = 'MaintenanceType')
setClass('contact', contains = 'ResponsibleParty')
setClass('publisher', contains = 'ResponsibleParty')
setClass('methods', contains = 'MethodsType')
setClass('project', contains = 'ResearchProjectType')
setClass('dataTable', contains = 'DataTableType')
setClass('spatialRaster', contains = 'SpatialRasterType')
setClass('spatialVector', contains = 'SpatialVectorType')
setClass('storedProcedure', contains = 'StoredProcedureType')
setClass('view', contains = 'ViewType')
setClass('otherEntity', contains = 'OtherEntityType')
setClass('description', contains = 'TextType')
setClass('maintenanceUpdateFrequency', contains = 'MaintUpFreqType')
setClass('changeDate', contains = 'xs:date')


#####  inst/xsd/eml.xsd  ####


setClass('ListOfadditionalMetadata', contains = 'list')
setClass('ListOfdescribes', contains = 'list')
setClass('eml', slots = c('access' = 'AccessType', 'dataset' = 'DatasetType', 'citation' = 'CitationType', 'software' = 'SoftwareType', 'protocol' = 'ProtocolType', 'additionalMetadata' = 'ListOfadditionalMetadata', 'packageId' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute', 'xml:lang' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('additionalMetadata', slots = c('describes' = 'ListOfdescribes', 'metadata' = 'character', 'id' = 'xml_attribute'), contains = c('eml-2.1.1'))
setClass('metadata', contains = c('eml-2.1.1'))
setClass('access', contains = 'AccessType')
setClass('dataset', contains = 'DatasetType')
setClass('citation', contains = 'CitationType')
setClass('software', contains = 'SoftwareType')

setClass('describes', contains = 'character')

setClass('proceduralStep', contains = 'ProcedureStepType')
setClass('protocol', contains = 'ProtocolType')
setClass('dataSource', contains = 'DatasetType')
setClass('methodStep', slots = c('dataSource' = 'ListOfdataSource'), contains = c('ProcedureStepType', 'eml-2.1.1'))
setClass('temporalCoverage', contains = c('TemporalCoverage', 'eml-2.1.1'))
setClass('taxonomicCoverage', contains = c('TaxonomicCoverage', 'eml-2.1.1'))
setClass('coverage', contains=c('Coverage'))
setClass('online', contains=c('OnlineType', 'PhysicalOnlineType'))
